### ISSUE TITLE
Official Review

### ISSUE THREAD

**Issue by micronet-challenge-submissions** [ZhongxiaYan/micronet#6]
Hello! Thanks so much for your entry!

We've reviewed your model and scoring calculations and everything checks out! We greatly appreciate the notebooks, they made it extremely easy for us to verify your test perplexity.

**Comment by micronet-challenge-submissions** [comment]
Also, could you provide us with an email you'd like to be contacted at?

**Comment by ZhongxiaYan** [comment]
Thanks for reviewing our entry so fast! You can contact us at zxyan@mit.edu (additionally hanrui@mit.edu and demiguo98@gmail.com).
